DROP TABLE if_src_job1;
DROP TABLE src_job1_part_a;
DROP TABLE src_job1_part_b;
CREATE TABLE if_src_job1(
	MARKET_CODE		VARCHAR2(4000) NOT NULL PRIMARY KEY
	,AREA_CODE		VARCHAR2(4000)
	,ITEM_CODE		VARCHAR2(4000)
	,KIND_CODE		VARCHAR2(4000)
	,SURVEY_DATE	TIMESTAMP
	,SURVEY_GRADE	VARCHAR2(4000)
	,TODAY_PRICE	NUMBER(15,3)
	,YESDAY_PRICE	NUMBER(15,3)
	,IN_QTY			NUMBER(15)
	,TRADE_QTY		NUMBER(15)
	,STEADY_TIMES	NUMBER(15)
	,BIGO			VARCHAR2(4000)
	,WORK_TYPE		VARCHAR2(4000)
	,INSPECT_SUM	NUMBER(15)
	,TOT_SURVEY		VARCHAR2(4000)
	,UPDATE_NO		VARCHAR2(4000)
	,COUNT_NO		VARCHAR2(4000)
	,UNIT_NO		VARCHAR2(4000)
	,RNF_CODE		VARCHAR2(4000)
	,EDATE			TIMESTAMP DEFAULT SYSTIMESTAMP
	,EFLAG			CHAR(1) DEFAULT 'I'	NOT NULL
);


CREATE TABLE src_job1_part_a(
	MARKET_CODE		VARCHAR2(4000) NOT NULL PRIMARY KEY
	,AREA_CODE		VARCHAR2(4000)
	,ITEM_CODE		VARCHAR2(4000)
	,KIND_CODE		VARCHAR2(4000)
	,SURVEY_DATE	TIMESTAMP
	,SURVEY_GRADE	VARCHAR2(4000)
	,INSPECT_SUM	NUMBER(15)
	,TOT_SURVEY		VARCHAR2(4000)
	,UPDATE_NO		VARCHAR2(4000)
	,COUNT_NO		VARCHAR2(4000)
	,UNIT_NO		VARCHAR2(4000)
	,RNF_CODE		VARCHAR2(4000)
);

CREATE TABLE src_job1_part_b(
	MARKET_CODE		VARCHAR2(4000) NOT NULL PRIMARY KEY
	,AREA_CODE		VARCHAR2(4000)
	,TODAY_PRICE	NUMBER(15,2)
	,YESDAY_PRICE	NUMBER(15,2)
	,IN_QTY			NUMBER(15)
	,TRADE_QTY		NUMBER(15)
	,STEADY_TIMES	NUMBER(15)
	,BIGO			VARCHAR2(4000)
	,WORK_TYPE		VARCHAR2(4000)
);

DELETE FROM src_job1_part_a;
INSERT INTO src_job1_part_a
(MARKET_CODE, AREA_CODE, ITEM_CODE, KIND_CODE, SURVEY_DATE, SURVEY_GRADE, INSPECT_SUM, TOT_SURVEY, UPDATE_NO, COUNT_NO, UNIT_NO, RNF_CODE)
VALUES
('MARKET-N','구역-N','ITEM-N','KIND-N',SYSTIMESTAMP,'F--',10,'TOTAL-N','UPD-A10','CNT-10','UNIT-10','RNF-110')
,('MARKET-O','구역-O','ITEM-O','KIND-O',SYSTIMESTAMP,'D+',50,'TOTAL-O','UPD-A11','CNT-11','UNIT-11','RNF-111')
,('MARKET-P','구역-P','ITEM-P','KIND-P',SYSTIMESTAMP,'B++',80,'TOTAL-P','UPD-A12','CNT-12','UNIT-12','RNF-112');

DELETE FROM src_job1_part_b;
INSERT INTO src_job1_part_b
(MARKET_CODE, AREA_CODE, TODAY_PRICE, YESDAY_PRICE, IN_QTY, TRADE_QTY, STEADY_TIMES, BIGO, WORK_TYPE)
VALUES
('MARKET-N','구역-N', 10028.03, 8012.87, 10, 100, 300, '비고무', 'H')
,('MARKET-O','구역-O', 9021.13, 9010.32, 70, 50, 104, '무비고', 'S')
,('MARKET-P','구역-P', 50154.03, 4705.69, 210, 30, 80, '고무비', 'M');

DELETE FROM if_src_job1;
DELETE FROM if_tgt_job1;
UPDATE src_job1_part_a SET SURVEY_DATE=SYSDATE
INSERT INTO if_src_job1 ( MARKET_CODE,AREA_CODE,ITEM_CODE,KIND_CODE,SURVEY_DATE,SURVEY_GRADE,INSPECT_SUM,TOT_SURVEY,UPDATE_NO,COUNT_NO,UNIT_NO,RNF_CODE ,TODAY_PRICE,YESDAY_PRICE,IN_QTY,TRADE_QTY,STEADY_TIMES,BIGO,WORK_TYPE ) SELECT  a.MARKET_CODE,a.AREA_CODE,a.ITEM_CODE,a.KIND_CODE,a.SURVEY_DATE,a.SURVEY_GRADE,a.INSPECT_SUM,a.TOT_SURVEY,a.UPDATE_NO,a.COUNT_NO,a.UNIT_NO,a.RNF_CODE ,b.TODAY_PRICE,b.YESDAY_PRICE,b.IN_QTY,b.TRADE_QTY,b.STEADY_TIMES,b.BIGO,b.WORK_TYPE FROM src_job1_part_a a 	LEFT OUTER JOIN src_job1_part_b b 	ON a.MARKET_CODE=b.MARKET_CODE WHERE TO_CHAR(a.SURVEY_DATE,'YYYYMMDD')=TO_CHAR(SYSDATE,'YYYYMMDD')
/*
UPDATE if_src_job1 SET EFLAG=:EFLAG WHERE MARKET_CODE=:MARKET_CODE;
INSERT INTO if_src_job1 (
	MARKET_CODE,AREA_CODE,ITEM_CODE,KIND_CODE,SURVEY_DATE,SURVEY_GRADE,INSPECT_SUM,TOT_SURVEY,UPDATE_NO,COUNT_NO,UNIT_NO,RNF_CODE
	,TODAY_PRICE,YESDAY_PRICE,IN_QTY,TRADE_QTY,STEADY_TIMES,BIGO,WORK_TYPE
) SELECT 
	a.MARKET_CODE,a.AREA_CODE,a.ITEM_CODE,a.KIND_CODE,a.SURVEY_DATE,a.SURVEY_GRADE,a.INSPECT_SUM,a.TOT_SURVEY,a.UPDATE_NO,a.COUNT_NO,a.UNIT_NO,a.RNF_CODE
	,b.TODAY_PRICE,b.YESDAY_PRICE,b.IN_QTY,b.TRADE_QTY,b.STEADY_TIMES,b.BIGO,b.WORK_TYPE
FROM
	src_job1_part_a a
		LEFT OUTER JOIN src_job1_part_b b
		ON a.MARKET_CODE=b.MARKET_CODE
WHERE
	TO_CHAR(a.SURVEY_DATE,'YYYYMMDD')=TO_CHAR(SYSDATE,'YYYYMMDD')
*/