DROP TABLE if_com_seed;
CREATE TABLE if_src_job2_com_seed (
	IDX 		FLOAT(126) NOT NULL PRIMARY KEY
	,COM_NAME	VARCHAR2(255)
	,ITEM_CD	FLOAT(126)
	,ITEM_NM	VARCHAR2(255)
	,ITEM_IMG	VARCHAR2(255)
	,DTL_IMG	VARCHAR2(255)
	,SUBJECT	VARCHAR2(1000)
	,ITEM_SPEC	VARCHAR2(4000)
	,CAUTION	VARCHAR2(4000)
	,EDATE		TIMESTAMP
	,EFLAG		CHAR(1) DEFAULT 'I' NOT NULL
)

DELETE FROM if_src_job2_com_seed;

select item_spec from com_seed where idx=431
select * from nls_database_parameters
where parameter = 'NLS_CHARACTERSET';

/*
SELECT * FROM if_src_job2_com_seed
WHERE EFLAG = 'I'

INSERT INTO if_src_job2_com_seed (
	IDX, COM_NAME, ITEM_CD, ITEM_NM, ITEM_IMG, DTL_IMG, SUBJECT, ITEM_SPEC, CAUTION
) 
SELECT
	IDX, COM_NAME, ITEM_CD, ITEM_NM, ITEM_IMG, DTL_IMG, SUBJECT, ITEM_SPEC, CAUTION
FROM COM_SEED

UPDATE if_src_job2_com_seed
SET EFLAG=:EFLAG, EDATE=:EDATE
WHERE IDX=:IDX




SELECT *
FROM
(
SELECT IDX, COUNT(*) CNT
FROM COM_SEED
GROUP BY IDX
)
WHERE CNT > 1
*/