
INSERT INTO IFR_IF_MGARAK (SURVEY_DATE,STAN_CODE,TRADE_UNIT,SPEC,GRADE,INTERVAL,SMALL,LARGE,AVERAGE,DUQTY,WEIGHT,SET_VALUE,REG_DATE)
VALUES(:SURVEY_DATE,:STAN_CODE,:TRADE_UNIT,:SPEC,:GRADE,:INTERVAL,:SMALL,:LARGE,:AVERAGE,:DUQTY,:WEIGHT,:SET_VALUE,SYSDATE)

INSERT INTO IFR_IF_MUTONG (
	SURVEY_DATE,ITEM_CODE,KIND_CODE,SURVEY_GRADE,TODAY_PRICE,YESDAY_PRICE,IN_QTY,TRADE_QTY,STEADY_TIMES,BIGO,WORK_TYPE
	,INSPECT_SUM,TOT_SURVEY,UPDATE_NO,COUNT_NO,UNIT_NO,RNF_CODE,AREA_CODE,MARKET_CODE,SURVEY_TYPE,SEND_FLAG,REG_DATE
) VALUES (
	:SURVEY_DATE,:ITEM_CODE,:KIND_CODE,:SURVEY_GRADE,:TODAY_PRICE,:YESDAY_PRICE,:IN_QTY,:TRADE_QTY,:STEADY_TIMES,:BIGO,:WORK_TYPE
	,:INSPECT_SUM,:TOT_SURVEY,:UPDATE_NO,:COUNT_NO,:UNIT_NO,:RNF_CODE,:AREA_CODE,:MARKET_CODE,:SURVEY_TYPE,'Y',:REG_DATE
)

select count(*) from IFR_IF_MGARAK;

delete from IFR_IF_MGARAK;



select count(*) from IFR_IF_MUTONG
select count(*) from IFS_IF_MUTONG where send_flag='N';

ALTER TABLE IFS_IF_MUTONG DROP COLUMN EDATE;
delete from IFR_IF_MUTONG;